### ISSUE TITLE
Get unit test coverage to 100%

### ISSUE THREAD

**Issue by tseaver** [zopefoundation/zope.catalog#1]
And then force it to stay that way via `setup.cfg`.

**Comment by jamadden** [comment]
Since https://github.com/zopefoundation/zope.catalog/commit/a986f7384de5e4bd53a69e42bee751e50c66632f we have 100% coverage, [verified by coveralls.io](https://coveralls.io/github/zopefoundation/zope.catalog). So I think we can close this.
