### ISSUE TITLE
ITextIndex broken under Python 3

### ISSUE THREAD

**Issue by jamadden** [zopefoundation/zope.catalog#5]
```
  File "//python3.5/site-packages/zope/catalog/text.py", line 41, in ITextIndex
    default="getSearchableText"
  File "//python3.5/site-packages/zope/schema/_bootstrapfields.py", line 307, in __init__
    super(MinMaxLen, self).__init__(**kw)
  File "//python3.5/site-packages/zope/schema/_bootstrapfields.py", line 158, in __init__
    self.default = default
  File "//python3.5/site-packages/zope/schema/_bootstrapfields.py", line 52, in __set__
    inst.validate(value)
...
  File "//python3.5/site-packages/zope/schema/_bootstrapfields.py", line 210, in _validate
    raise WrongType(value, self._type, self.__name__)
zope.configuration.xmlconfig.ZopeXMLConfigurationError: File "//python3.5/site-packages/zope/app/catalog/configure.zcml", line 3.2-3.33
    ZopeXMLConfigurationError: File "/python3.5/site-packages/zope/app/catalog/classes.zcml", line 3.1-3.55
    ZopeXMLConfigurationError: File "/python3.5/site-packages/zope/catalog/classes.zcml", line 42.1
    ConfigurationError: ('Invalid value for', 'class', "('getSearchableText', <class 'bytes'>, '')")
```

**Comment by jamadden** [comment]
The issue is the field definition:
```
field_name = zope.schema.BytesLine(
        title=_(u"Field Name"),
        description=_(u"Name of the field to index"),
        default="getSearchableText"
        )
```

Should that be a `NativeStringLine` instead? Or should the default really be `b"getSearchableText"`? 

I've tested that `NativeStringLine` solves the problem for zope.app.catalog.

**Comment by mgedmin** [comment]
Object attribute names are byte strings on Python 2 and unicode strings on Python 3, so NativeStringLine seems fine to me.

ZODB doesn't support sharing the same database between Python 2 and Python 3 clients, so there shouldn't be any database compatibility concerns with existing TextIndex objects.

**Comment by jamadden** [comment]
> Object attribute names are byte strings on Python 2 and unicode strings on Python 3, so NativeStringLine seems fine to me.

Done in #6.

> ZODB doesn't support sharing the same database between Python 2 and Python 3 clients, so there shouldn't be any database compatibility concerns with existing TextIndex objects.

And as you pointed out, NativeStringLine is exactly the same as ByteLine on Python 2, and these objects simply couldn't be created under Python 3, so there shouldn't be any *code* compatibility concerns either.
